### ISSUE TITLE
运算符 INTERVAL 页面：实例5 的两个SQL执行结果跟实际执行结果不一致

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixone-cloud/moc-docs#125]
**URL:**
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/Reference/Operators/interval/#5

**MO-版本：**
v1.0.0-rc2 

**问题描述：**
参考书册=>函数与操作符=》运算符=》INTERVAL  页面中示例5的SQL执行接口跟实际不符，如下图:
**文档截图：**
![1699606274507](https://github.com/matrixone-cloud/moc-docs/assets/91644845/675ef0a9-1750-4936-b643-14e01603e3c7)
**实际本地数据库执行截图：**
![1699607681946](https://github.com/matrixone-cloud/moc-docs/assets/91644845/4e4bea2f-ac35-40e0-a2d8-773d8c979f9d)
**实际云线上执行截图：**
![1699607789037](https://github.com/matrixone-cloud/moc-docs/assets/91644845/f856a5b8-f6c7-4097-b2bb-bf72a98c9e50)

**Comment by dengn** [comment]
把文档里的例子改掉吧，改成现在mo输出的结果

**Comment by dengn** [comment]
fixed
