### ISSUE TITLE
“算数运算符概述” 页面，例子“表达式 5.05 / 0.014……”表述不清楚，且这个表达式的执行结果跟实际执行结果不一致；

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixone-cloud/moc-docs#132]
**页面地址：**
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/Reference/Operators/operators/arithmetic-operators/arithmetic-operators-overview/#_2

**问题描述：**
“例如，表达式 5.05 / 0.014 的 ……”，这块的表述不清楚，且这个表达式（ 5.05 / 0.014）的执行结果跟实际执行结果不一致；

**问题截图：**
![1699611884741](https://github.com/matrixone-cloud/moc-docs/assets/91644845/ba68565c-2ca8-4a53-be7d-ee157310618c)

**表达式的实际执行结果截图：**
![1699612221347](https://github.com/matrixone-cloud/moc-docs/assets/91644845/a5f2d98b-c5e9-4c43-ae75-2b0e3fef7fe1)
![1699612238459](https://github.com/matrixone-cloud/moc-docs/assets/91644845/354065a4-289d-435c-9b39-f2175969c3a4)

**Comment by dengn** [comment]
把文档更新掉吧 @yanghaitao5000

**Comment by yanghaitao5000** [comment]
已经提PR了：https://github.com/matrixone-cloud/moc-docs/pull/187
