### ISSUE TITLE
MOC中CU和存储配额和统计问题

### ISSUE THREAD

**Issue by WuMenglong** [matrixone-cloud/moc-docs#140]
MOC中对于免费赠送的CU数描述上下不太一致，存储在使用load data local导入本地tpch 1g数据后，今天一直没有看到存储有变化，表现如下图：

![image](https://github.com/matrixone-cloud/moc-docs/assets/90299197/b1130015-a2ca-4ce7-a69c-f3b06e2913ac)

**Comment by dengn** [comment]
免费额度是5000万，这是针对每个账号的。每个账号允许最多创建5个实例，每个1000万。
存储一直没动这个是个bug，还在修复。

**Comment by dengn** [comment]
@yangj1211 免费额度和账号具体的策略要更新上去。

**Comment by dengn** [comment]
verified.
