### ISSUE TITLE
是否可以在MO Cloud中增加一个“在线客服”

### ISSUE THREAD

**Issue by WuMenglong** [matrixone-cloud/moc-docs#60]
如题，是否可以在MO Cloud中增加一个“在线客服”，来高效解决问题或将问题引导反馈至社区

**Comment by dengn** [comment]
现在有这个功能了，在下面的这个小筐里

<img width="1440" alt="image" src="https://github.com/matrixone-cloud/moc-docs/assets/4965857/ba980a34-758b-4d32-89f4-1d2a5ba1f8c6">
